### ISSUE TITLE
Dialog Closing

### ISSUE THREAD

**Issue by Riolku** [kuzudb/kuzu-ui#26]
Currently, the dialog closing message updates every 0.1 seconds. In my opinion, this is non-standard and distracting. Instead, let's just update it every second.

**Comment by mewim** [comment]
LOL. I set this intentionally as I prefer it to be 0.1 seconds. But if it’s annoying for others, I can also change it back to 1.

**Comment by Riolku** [comment]
Feel free to collect feedback from others, I might very well be the outlier, but I think it makes sense to be consistent with other websites.
